// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwexosucsusazckllkra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3ZXhvc3Vjc3VzYXpja2xsa3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDI4NTQsImV4cCI6MjA3MzUxODg1NH0.CYnM03UHqh4qZNMssnHdP_DUhs76gQvgXw3ZKlwqnQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});